### ISSUE TITLE
Global Snackbar System

### ISSUE THREAD

**Issue by CodeChrisB** [CodeChrisB/bookless#133]
## Todo
   - [ ] A snackbar on root level
   - [ ] A service which controlls the Snackbar

## Result

- [ ] A globally callable function which triggers a Snackbar

**Comment by CodeChrisB** [comment]
Name change
